# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8abce89931d0ef58a96b9c7ee8dd02e56bd6ecc546bf7ceb4b6695c171b1f320a62c4459ecb979e5ff0bc79cea89c1a281381ccf9dfb2b30d6ae6835cbc47acb

test:
  secret_key_base: 2699223219a9c5713cab7fd50a4e469479fc4745dfb1468b443df2224be8f7a0faa3884120a9c7ed2da0c58d3c3e3a9b909e0fe1f4d481028d87a69b2f500926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
